In [ ]:
##Tutorial from Krish Naik and Ninjas mixed

In [33]:
import numpy as np

In [21]:
my_list=[1,2,3,4]
arr=np.array(my_list)
arr


array([1, 2, 3, 4])

In [22]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4]


In [7]:
arr.shape

(4,)

In [24]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
my_list3=[9,20,30,40]
my_list4=[10,80,90,100]

arr_2=np.array([my_list1,my_list2,my_list3,my_list4])
arr_2

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  20,  30,  40],
       [ 10,  80,  90, 100]])

In [29]:
arr_2[2:,1:3]

array([[20, 30],
       [80, 90]])

In [30]:
arr_2[1:3,1:3]

array([[ 6,  7],
       [20, 30]])

In [32]:
arr_2[2:3,1:]

array([[20, 30, 40]])

In [47]:
arr=np.arange(0,20).reshape(1,20)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

### Coding Ninjas

In [1]:
import numpy as npa

In [5]:
a=[1,2,3]
b=npa.array(a)
b
type(b)

numpy.ndarray

Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.


In [8]:
list=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
npa.array((list))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.

In [22]:
b=npa.zeros(10,dtype=int)
b[4]=1
for i in b:
    print(i,end=" ")

0 0 0 0 1 0 0 0 0 0 

In [25]:
b=npa.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [4]:
npa.arange(10)
npa.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a = npa.array([0, 1, 2, 3])
a.shape

(4,)

In [6]:
a=npa.array([0,1])
a.shape

(2,)

In [7]:
npa.array([])

array([2])

In [10]:
npa.random.randint(10, 4)

ValueError: low >= high