In [1]:
import numpy as np

In [5]:
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
a=[1,2,3,'4','a',4.5]
b=np.array(a)
print(b)
print(type(b))

['1' '2' '3' '4' 'a' '4.5']
<class 'numpy.ndarray'>


In [17]:
b=np.ones(2)
(print(b))

[1. 1.]


In [15]:
b=np.ones((2,3),dtype=int)
print(b)

[[1 1 1]
 [1 1 1]]


In [19]:
b=np.zeros(2)
print(b)

[0. 0.]


In [28]:
a=np.empty(4, dtype=int)
print(a)

[0 0 0 0]


##Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.##

In [30]:
a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b=np.array(a)
b
type(b)

numpy.ndarray